We have a 4x4 grid, and we know there’s a mouse trapped in one of the cells. We want to figure out which cell it’s in, but we can only ask queries of a specific form. Given a subset of the cells, we can “scan” our grid to know whether there’s a mouse within that subset or not, but not where it is exactly.

How would we figure out where the mouse is using the fewest number of scans?

Binary search: Repeatedly dividing the grid in half and scanning each half until the mouse is found.

In [277]:
import random
import numpy as np
import pandas as pd

In [269]:
class Grid:
    
    def __init__(self, size = 4):
        self.n_rows = size
        self.n_cols = size
        self.mouse = (random.randint(1, self.n_rows -1), random.randint(1, self.n_cols -1))
        self.table = np.array([1 if row == self.mouse[0] and col == self.mouse[1] else 0 \
                               for row in range(self.n_rows) for col in range(self.n_cols) ]).reshape(self.n_rows,self.n_cols)
        print(self.table)
        

    def half_selection(self):
            
            iterations = 0
            X_pos_bin = '' # binary string to retrieve the original X position of the mouse
            Y_pos_bin = '' # binary string to retrieve the original Y position of the mouse
            
            while self.table.shape[1] > 1: # until we searches along all the X axis
                
                table_R = np.array([self.table[row][col] for row in range(self.n_rows) for col in range(self.n_cols) \
                                   if col >= self.n_cols // 2]).reshape(self.n_rows, self.n_cols // 2) # half table right
                
                if np.sum(table_R) == 1:
                    self.table = table_R
                    X_pos_bin += '1'
                else:
                    self.table = np.array([self.table[row][col] for row in range(self.n_rows) for col in range(self.n_cols) \
                                   if col < self.n_cols // 2]).reshape(self.n_rows, self.n_cols // 2) # half table left
                    X_pos_bin += '0'
                    
                self.n_cols = self.n_cols // 2
                iterations += 1
                
                ######################################################
                print('iteration:', iterations)
                print(self.table) 
                print('table shape:', self.table.shape)
                print('\n')
                ######################################################
                
            while self.table.shape[0] > 1: # until we searches along all the Y axis
                
                table_U = np.array([self.table[row][col] for row in range(self.n_rows) for col in range(self.n_cols) \
                                   if row < self.n_rows // 2]).reshape(self.n_rows // 2, self.n_cols) # half table up
                
                if np.sum(table_U) == 1:
                    self.table = table_U
                    Y_pos_bin += '0'
                else:
                    self.table = np.array([self.table[row][col] for row in range(self.n_rows) for col in range(self.n_cols) \
                                   if row >= self.n_rows // 2]).reshape(self.n_rows // 2, self.n_cols) # half table down
                    Y_pos_bin += '1'
                
                self.n_rows = self.n_rows // 2
                iterations += 1

                ######################################################
                print('iteration:', iterations)
                print(self.table) 
                print('table shape:', self.table.shape)
                print('\n')
                ######################################################
            
            X_pos = int(X_pos_bin, 2)
            Y_pos = int(Y_pos_bin,2)
        
            return [X_pos, Y_pos], iterations

In [279]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

my_grid = Grid(16)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [280]:
my_grid.half_selection()

iteration: 1
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
table shape: (16, 8)


iteration: 2
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
table shape: (16, 4)


iteration: 3
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
table shape: (16, 2)


iteration: 4
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]]
table shape: (16, 1)


iteration: 5
[[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]]
table shape: (8, 1)


iteration: 6
[[0]
 [0]
 [1]
 [0]]
table shape: (4, 1)


iteration: 7
[[1]
 [0]]
table shape: (2, 1)


it

([11, 10], 8)